[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.24"

[features]
seeds = true
skip-lint = false

[programs.localnet]
yevefi = "EdG4rQqC9LCY4MQWLGXerQ7h1LknKRmSiHL1upCNEdqD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jimmyphong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/04_init_reward.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metaplex_token_metadata_program.so"
